include $(THEOS)/makefiles/common.mk

TOOL_NAME = Maxvnode++
Maxvnode++_FILES = maxvnode++.c
Maxvnode++_CFLAGS += -fvisibility=hidden
Maxvnode++_FRAMEWORKS = CoreFoundation

include $(THEOS_MAKE_PATH)/tool.mk